<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<?= $block->getChildHtml('header.skip') ?>

<nav class="header-content" role="navigation">

    <div class="header-main">
        <div class="container">
            <div class="header-main-inner">

                <div class="header-main-nav">
                    <button type="button" class="nav-toggle" data-action="toggle-nav">
                        <span><?= __('Navigation') ?></span>
                    </button>
                </div>

                <div class="header-main-logo">
                    <?= $block->getChildHtml('header.logo'); ?>
                </div>

                <div class="header-nav">
                    <?= $block->getChildHtml('header.nav'); ?>
                </div>

                <div class="header-main-links">
                    <div class="header-main-links-inner list list-space-none">
                        <div>
                            <div class="drop-outer" data-xt-drop>
                                <button type="button" class="btn btn-primary btn-tiny">
                                    <?= __('My Account') ?>
                                </button>
                                <div class="drop">
                                    <div class="drop-inner">
                                        <div class="content">
                                            <?= $block->getChildHtml('header.links.store') ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div>
                            <?= $block->getChildHtml('header.links.additional') ?>
                        </div>
                    </div>
                </div>

                <div class="header-main-right">
                    <div class="header-main-right-inner">
                        <?= $block->getChildHtml('search.wrapper') ?>
                        <?= $block->getChildHtml('minicart.wrapper') ?>
                    </div>
                </div>

            </div>
        </div>
    </div>

</nav>

<div class="header-mobile">
    <div class="header-mobile-backdrop" data-action="toggle-nav"></div>
    <div class="header-mobile-content nav-sections"> <!-- .nav-sections for closing menu on swipeleft -->
        <div class="header-mobile-content-inner">

            <?= $block->getChildHtml('header.mobile'); ?>

        </div>
    </div>
</div>
