<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<ul class="list"
    data-mage-init='{"menu":
        {"responsive":true,
        "expanded":true,
        "position":{"my":"left top","at":"left bottom"}}}'>
    <?= /* @escapeNotVerified */ $_menu ?>
    <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
</ul>
