<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<nav class="footer-content" role="navigation">

    <div class="footer-top">
        <div class="container">

            <div class="footer-top-inner">

                <div class="col col-6 col-4-sm col-3-md col-2-lg">
                  <?= $block->getChildHtml('footer.links'); ?>
                </div>

                <div class="col col-6 col-4-sm col-3-md col-2-lg">
                  <?= $block->getChildHtml('footer.links.additional') ?>
                </div>

                <div class="col col-12 col-4-sm col-3-lg">
                  <?= $block->getChildHtml('footer.subscribe'); ?>
                </div>

            </div>

        </div>
    </div>

    <div class="footer-bottom">
        <div class="container">

            <div class="footer-bottom-inner">

                <div class="footer-bottom-left">
                    <?= $block->getChildHtml('copyright'); ?>
                </div>

                <div class="footer-bottom-right">
                    <?= $block->getChildHtml('language.switcher.wrapper') ?>
                    <?= $block->getChildHtml('currency.switcher.wrapper'); ?>
                    <?= $block->getChildHtml('store.switcher.wrapper'); ?>
                </div>

            </div>

        </div>
    </div>

</nav>
