<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<nav class="footer-content" role="navigation">

    <div class="footer-bottom">
        <div class="container-fluid">

            <div class="footer-bottom-inner">

                <div class="footer-bottom-left">
                    <?= $block->getChildHtml('copyright.checkout'); ?>
                </div>

            </div>

        </div>
    </div>

</nav>
