<div class="drop-container" data-xt-drop>
    <button type="button" class="btn btn-primary">
        xtend drop
    </button>
    <div class="drop">
        <div class="drop-inner">
            <ul class="list list-drop">
                <li>
                    <a href="#">Lorem Ipsum</a>
                </li>
                <li>
                    <button type="button">Dolor sit</button>
                </li>
                <li>
                    <button type="button">Amet</button>
                </li>
            </ul>
        </div>
    </div>
</div>

<div data-xt-overlay>
    <button type="button" class="btn btn-primary">
        xtend modal
    </button>
    <div class="overlay-outer">
        <div class="overlay">
            <div class="overlay-inner">
                <button type="button" class="btn btn-close"></button>
                <h2>Lorem ipsum</h2>
                <h5>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed cursus, lectus quis ornare volutpat,
                    ligula nulla sollicitudin nunc, ut commodo nulla enim nec nisi.</p>
                <p>Morbi sodales, dolor a iaculis ornare, velit justo lacinia erat, pretium sollicitudin dui sem id
                    justo.</p>
            </div>
        </div>
    </div>
</div>

<button type="button" class="action primary open-modal-test-1">
    <span>Modal</span>
</button>
<button type="button" class="action primary open-modal-test-2">
    <span>Modal screen</span>
</button>
<div id="modal-test-1" style="display:none;">
    <h3>Title h2</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dictum velit condimentum efficitur feugiat. Sed sit amet leo nunc. Sed consectetur lectus a erat commodo, id facilisis metus sagittis. Morbi ullamcorper massa vel diam commodo, eget fermentum nisi aliquam. Vivamus gravida bibendum diam.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dictum velit condimentum efficitur feugiat. Sed sit amet leo nunc. Sed consectetur lectus a erat commodo, id facilisis metus sagittis. Morbi ullamcorper massa vel diam commodo, eget fermentum nisi aliquam. Vivamus gravida bibendum diam.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dictum velit condimentum efficitur feugiat. Sed sit amet leo nunc. Sed consectetur lectus a erat commodo, id facilisis metus sagittis. Morbi ullamcorper massa vel diam commodo, eget fermentum nisi aliquam. Vivamus gravida bibendum diam.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dictum velit condimentum efficitur feugiat. Sed sit amet leo nunc. Sed consectetur lectus a erat commodo, id facilisis metus sagittis. Morbi ullamcorper massa vel diam commodo, eget fermentum nisi aliquam. Vivamus gravida bibendum diam.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dictum velit condimentum efficitur feugiat. Sed sit amet leo nunc. Sed consectetur lectus a erat commodo, id facilisis metus sagittis. Morbi ullamcorper massa vel diam commodo, eget fermentum nisi aliquam. Vivamus gravida bibendum diam.</p>
</div>
<div id="modal-test-2" style="display:none;">
    <h3>Title h2</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dictum velit condimentum efficitur feugiat. Sed sit amet leo nunc. Sed consectetur lectus a erat commodo, id facilisis metus sagittis. Morbi ullamcorper massa vel diam commodo, eget fermentum nisi aliquam. Vivamus gravida bibendum diam.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dictum velit condimentum efficitur feugiat. Sed sit amet leo nunc. Sed consectetur lectus a erat commodo, id facilisis metus sagittis. Morbi ullamcorper massa vel diam commodo, eget fermentum nisi aliquam. Vivamus gravida bibendum diam.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dictum velit condimentum efficitur feugiat. Sed sit amet leo nunc. Sed consectetur lectus a erat commodo, id facilisis metus sagittis. Morbi ullamcorper massa vel diam commodo, eget fermentum nisi aliquam. Vivamus gravida bibendum diam.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dictum velit condimentum efficitur feugiat. Sed sit amet leo nunc. Sed consectetur lectus a erat commodo, id facilisis metus sagittis. Morbi ullamcorper massa vel diam commodo, eget fermentum nisi aliquam. Vivamus gravida bibendum diam.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dictum velit condimentum efficitur feugiat. Sed sit amet leo nunc. Sed consectetur lectus a erat commodo, id facilisis metus sagittis. Morbi ullamcorper massa vel diam commodo, eget fermentum nisi aliquam. Vivamus gravida bibendum diam.</p>
</div>
<script type="text/javascript">

    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
    ], function($, modal){

        // make modal-test-1
        var modaltest1 = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            modalClass: 'modal-test-1',
            title: $.mage.__('Modal test 1'),
            buttons: [{
                text: $.mage.__('Close'),
                class: '',
                click: function () {
                    this.closeModal();
                }
            }]
        };

        // open modal-test-1
        modal(modaltest1, $('#modal-test-1'));
        $('.open-modal-test-1').on('click',function(){
            $('#modal-test-1').modal("openModal");
        });

        // make modal-test-2
        var modaltest2 = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            modalClass: 'overlay-screen',
            title: $.mage.__('Modal test 2'),
            buttons: [{
                text: $.mage.__('Close'),
                class: '',
                click: function () {
                    this.closeModal();
                }
            }]
        };

        // open modal-test-1
        modal(modaltest2, $('#modal-test-2'));
        $('.open-modal-test-2').on('click',function(){
            $('#modal-test-2').modal("openModal");
        });

    });
</script>

<div class="drop-outer-0">
  <button type="button" class="button">
    <span>Dropdown</span>
  </button>
  <div data-role="dropdownDialog"
       data-mage-init='{"dropdownDialog":{
        "appendTo":".drop-outer-0",
        "triggerTarget":".drop-outer-0 > .button",
        "timeout": "2000",
        "closeOnMouseLeave": false,
        "closeOnEscape": true,
        "triggerClass":"active",
        "parentClass":"active",
        "buttons":[]}}'>
    <ul>
      <li>
        <button type="button">Lorem</button>
      </li>
      <li>
        <button type="button">Lorem ipsum</button>
      </li>
      <li>
        <button type="button">Lorem ipsum</button>
      </li>
    </ul>
  </div>
</div>

<div data-mage-init='{"tabs":{"openedState": "active", "collapsibleElement": "ul > li", "content": "> div"}}'>
  <ul>
    <li>
      <a href="#one">
        title1
      </a>
    </li>
    <li>
      <a href="#two">
        title2
      </a>
    </li>
    <li>
      <a href="#three">
        title3
      </a>
    </li>
  </ul>
  <div id="one">
    <h4>Content one</h4>
  </div>
  <div id="two">
    <h4>Content two</h4>
  </div>
  <div id="three">
    <h4>Content three</h4>
  </div>
</div>
