<h5>Magento modal</h5>
<button type="button" class="action primary open-modal-test-1">
    <span>Modal</span>
</button>
<button type="button" class="action primary open-modal-test-2">
    <span>Modal screen</span>
</button>
<div id="modal-test-1" style="display:none;">
    <h3>Title h2</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dictum velit condimentum efficitur feugiat. Sed sit amet leo nunc. Sed consectetur lectus a erat commodo, id facilisis metus sagittis. Morbi ullamcorper massa vel diam commodo, eget fermentum nisi aliquam. Vivamus gravida bibendum diam.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dictum velit condimentum efficitur feugiat. Sed sit amet leo nunc. Sed consectetur lectus a erat commodo, id facilisis metus sagittis. Morbi ullamcorper massa vel diam commodo, eget fermentum nisi aliquam. Vivamus gravida bibendum diam.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dictum velit condimentum efficitur feugiat. Sed sit amet leo nunc. Sed consectetur lectus a erat commodo, id facilisis metus sagittis. Morbi ullamcorper massa vel diam commodo, eget fermentum nisi aliquam. Vivamus gravida bibendum diam.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dictum velit condimentum efficitur feugiat. Sed sit amet leo nunc. Sed consectetur lectus a erat commodo, id facilisis metus sagittis. Morbi ullamcorper massa vel diam commodo, eget fermentum nisi aliquam. Vivamus gravida bibendum diam.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dictum velit condimentum efficitur feugiat. Sed sit amet leo nunc. Sed consectetur lectus a erat commodo, id facilisis metus sagittis. Morbi ullamcorper massa vel diam commodo, eget fermentum nisi aliquam. Vivamus gravida bibendum diam.</p>
</div>
<div id="modal-test-2" style="display:none;">
    <h3>Title h2</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dictum velit condimentum efficitur feugiat. Sed sit amet leo nunc. Sed consectetur lectus a erat commodo, id facilisis metus sagittis. Morbi ullamcorper massa vel diam commodo, eget fermentum nisi aliquam. Vivamus gravida bibendum diam.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dictum velit condimentum efficitur feugiat. Sed sit amet leo nunc. Sed consectetur lectus a erat commodo, id facilisis metus sagittis. Morbi ullamcorper massa vel diam commodo, eget fermentum nisi aliquam. Vivamus gravida bibendum diam.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dictum velit condimentum efficitur feugiat. Sed sit amet leo nunc. Sed consectetur lectus a erat commodo, id facilisis metus sagittis. Morbi ullamcorper massa vel diam commodo, eget fermentum nisi aliquam. Vivamus gravida bibendum diam.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dictum velit condimentum efficitur feugiat. Sed sit amet leo nunc. Sed consectetur lectus a erat commodo, id facilisis metus sagittis. Morbi ullamcorper massa vel diam commodo, eget fermentum nisi aliquam. Vivamus gravida bibendum diam.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dictum velit condimentum efficitur feugiat. Sed sit amet leo nunc. Sed consectetur lectus a erat commodo, id facilisis metus sagittis. Morbi ullamcorper massa vel diam commodo, eget fermentum nisi aliquam. Vivamus gravida bibendum diam.</p>
</div>
<script type="text/javascript">

    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
    ], function($, modal){

        // make modal-test-1
        var modaltest1 = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            modalClass: 'modal-test-1',
            title: $.mage.__('Modal test 1'),
            buttons: [{
                text: $.mage.__('Close'),
                class: '',
                click: function () {
                    this.closeModal();
                }
            }]
        };

        // open modal-test-1
        modal(modaltest1, $('#modal-test-1'));
        $('.open-modal-test-1').on('click',function(){
            $('#modal-test-1').modal("openModal");
        });

        // make modal-test-2
        var modaltest2 = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            modalClass: 'overlay-screen',
            title: $.mage.__('Modal test 2'),
            buttons: [{
                text: $.mage.__('Close'),
                class: '',
                click: function () {
                    this.closeModal();
                }
            }]
        };

        // open modal-test-1
        modal(modaltest2, $('#modal-test-2'));
        $('.open-modal-test-2').on('click',function(){
            $('#modal-test-2').modal("openModal");
        });

    });
</script>

<br/>
<h5>Magento dropdown</h5>
<div class="drop-outer-0">
  <button type="button" class="button">
    <span>Dropdown</span>
  </button>
  <div data-role="dropdownDialog"
       data-mage-init='{"dropdownDialog":{
        "appendTo":".drop-outer-0",
        "triggerTarget":".drop-outer-0 > .button",
        "timeout": "2000",
        "closeOnMouseLeave": false,
        "closeOnEscape": true,
        "triggerClass":"active",
        "parentClass":"active",
        "buttons":[]}}'>
    <ul>
      <li>
        <button type="button">Lorem</button>
      </li>
      <li>
        <button type="button">Lorem ipsum</button>
      </li>
      <li>
        <button type="button">Lorem ipsum</button>
      </li>
    </ul>
  </div>
</div>

<br/>
<h5>Magento tabs</h5>
<div data-mage-init='{"tabs":{"openedState": "active", "collapsibleElement": "ul > li", "content": "> div"}}'>
  <ul>
    <li>
      <a href="#one">
        title1
      </a>
    </li>
    <li>
      <a href="#two">
        title2
      </a>
    </li>
    <li>
      <a href="#three">
        title3
      </a>
    </li>
  </ul>
  <div id="one">
    <h4>Content one</h4>
  </div>
  <div id="two">
    <h4>Content two</h4>
  </div>
  <div id="three">
    <h4>Content three</h4>
  </div>
</div>

<br/>
<h5>xtend drop</h5>
<div class="drop-container" data-xt-drop>
    <button type="button" class="btn btn-primary">
        xtend drop
    </button>
    <div class="drop">
        <div class="drop-inner">
            <ul class="list list-drop">
                <li>
                    <a href="#">Lorem Ipsum</a>
                </li>
                <li>
                    <button type="button">Dolor sit</button>
                </li>
                <li>
                    <button type="button">Amet</button>
                </li>
            </ul>
        </div>
    </div>
</div>

<br/>
<h5>xtend overlay</h5>
<div data-xt-overlay>
    <button type="button" class="btn btn-primary">
        xtend modal
    </button>
    <div class="overlay-outer">
        <div class="overlay">
            <div class="overlay-inner">
                <button type="button" class="btn btn-close"></button>
                <h2>Lorem ipsum</h2>
                <h5>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed cursus, lectus quis ornare volutpat,
                    ligula nulla sollicitudin nunc, ut commodo nulla enim nec nisi.</p>
                <p>Morbi sodales, dolor a iaculis ornare, velit justo lacinia erat, pretium sollicitudin dui sem id
                    justo.</p>
            </div>
        </div>
    </div>
</div>

<br/>
<h1>Lorem ipsum dolot sit amet <code>h1</code></h1>
<h2>Lorem ipsum dolot sit amet <code>h2</code></h2>
<h3>Lorem ipsum dolot sit amet <code>h3</code></h3>
<h4>Lorem ipsum dolot sit amet <code>h4</code></h4>
<h5>Lorem ipsum dolot sit amet <code>h5</code></h5>
<h6>Lorem ipsum dolot sit amet <code>h6</code></h6>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <a href="#">Link</a>, <strong>bold</strong> <em>italic</em>. Aenean fringilla orci sit amet quam aliquam vestibulum. Nullam ut scelerisque elit. Sed a nibh dui. Donec ultricies dui vel metus pulvinar, vel sagittis tellus venenatis. Nulla ac eleifend velit, accumsan consectetur sem. Aenean molestie dapibus sodales.</p>
<p>Phasellus suscipit enim ex, sed volutpat lorem feugiat id. Vestibulum congue volutpat posuere. Sed ligula ex, imperdiet ac leo id, blandit interdum sapien. Nam libero lorem, ultricies nec commodo eget, lobortis in dolor. Duis quis eros vel enim auctor tempor. Aliquam molestie dictum purus. Praesent pharetra auctor convallis. Nunc efficitur nulla tortor, ut ullamcorper elit convallis at. Maecenas at velit tempus, sodales nunc eu, pretium magna. Integer gravida tellus non orci interdum, nec pharetra urna ultricies.</p>
<ul class="default-lists">
    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fringilla orci sit amet quam aliquam vestibulum. Nullam ut scelerisque elit. Sed a nibh dui. Donec ultricies dui vel metus pulvinar, vel sagittis tellus venenatis. Nulla ac eleifend velit, accumsan consectetur sem. Aenean molestie dapibus sodales.</li>
    <li>Phasellus suscipit enim ex, sed volutpat lorem feugiat id. Vestibulum congue volutpat posuere. Sed ligula ex, imperdiet ac leo id, blandit interdum sapien. Nam libero lorem, ultricies nec commodo eget, lobortis in dolor. Duis quis eros vel enim auctor tempor. Aliquam molestie dictum purus. Praesent pharetra auctor convallis. Nunc efficitur nulla tortor, ut ullamcorper elit convallis at. Maecenas at velit tempus, sodales nunc eu, pretium magna. Integer gravida tellus non orci interdum, nec pharetra urna ultricies.</li>
</ul>
<dl class="dl-block">
    <dt>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean fringilla orci sit amet quam aliquam vestibulum. Nullam ut scelerisque elit. Sed a nibh dui. Donec ultricies dui vel metus pulvinar, vel sagittis tellus venenatis. Nulla ac eleifend velit, accumsan consectetur sem. Aenean molestie dapibus sodales.</dt>
    <dd>Phasellus suscipit enim ex, sed volutpat lorem feugiat id. Vestibulum congue volutpat posuere. Sed ligula ex, imperdiet ac leo id, blandit interdum sapien. Nam libero lorem, ultricies nec commodo eget, lobortis in dolor. Duis quis eros vel enim auctor tempor. Aliquam molestie dictum purus. Praesent pharetra auctor convallis. Nunc efficitur nulla tortor, ut ullamcorper elit convallis at. Maecenas at velit tempus, sodales nunc eu, pretium magna. Integer gravida tellus non orci interdum, nec pharetra urna ultricies.</dd>
</dl>
<dl class="dl-line">
    <dt>Lorem ipsum dolor sit amet</dt>
    <dd>Aenean fringilla orci sit amet quam aliquam vestibulum.</dd>
    <dt>Lorem ipsum dolor sit amet</dt>
    <dd>Aenean fringilla orci sit amet quam aliquam vestibulum. Nullam ut scelerisque elit. Sed a nibh dui.</dd>
</dl>

<br/>
<div class="list align-items-center">
    <button type="button" class="btn btn-primary">
        btn-primary
    </button>
    <button type="button" class="btn btn-primary-border">
        btn-primary-border
    </button>
    <button type="button" class="btn btn-secondary">
        btn-secondary
    </button>
    <button type="button" class="btn btn-secondary-border">
        btn-secondary-border
    </button>
    <button type="button" class="btn btn-link">
        btn-link
    </button>
</div>

<br/>
<div class="list align-items-center">
    <button type="button" class="btn btn-secondary btn-tiny">
        tiny
    </button>
    <button type="button" class="btn btn-secondary btn-small">
        small
    </button>
    <button type="button" class="btn btn-secondary btn-medium">
        medium
    </button>
    <button type="button" class="btn btn-secondary btn-big">
        big
    </button>
    <button type="button" class="btn btn-secondary btn-giant">
        giant
    </button>
</div>

<br/>
<form novalidate data-mage-init='{"validation": {"errorClass": "mage-error"}}'>

    <h5>Test checkbox and radio</h5>
    <div class="form-group">
        <input type="checkbox" name="checkbox-0" id="checkbox-0" data-validate="{required:true}">
        <label for="checkbox-0">
            <span>
                <?= __('I read and accept the <a href="%1" target="_blank">sales conditions</a> and the <a href="%2" target="_blank">privacy policy</a>.', $block->getUrl('conditions'), $block->getUrl('privacy')) ?>
            </span>
        </label>
    </div>
    <div class="form-group">
        <input type="radio" name="radio-0" id="radio-0" data-validate="{required:true}">
        <label for="radio-0">
            <span>
                <?= __('I read and accept the <a href="%1" target="_blank">sales conditions</a> and the <a href="%2" target="_blank">privacy policy</a>.', $block->getUrl('conditions'), $block->getUrl('privacy')) ?>
            </span>
        </label>
    </div>

    <h5>Test inline checkbox</h5>
    <div class="form-group">
        <div class="form-group-inline">
            <div class="form-group">
                <input type="checkbox" name="checkbox-1" id="checkbox-1" data-validate="{required:true}">
                <label for="checkbox-1">
                    checkbox 1
                </label>
            </div>
            <div class="form-group">
                <input type="checkbox" name="checkbox-2" id="checkbox-2" data-validate="{required:true}">
                <label for="checkbox-2">
                    checkbox 2
                </label>
            </div>
            <div class="form-group">
                <input type="radio" name="radio-1-2" id="radio-1" data-validate="{required:true}">
                <label for="radio-1">
                    radio 1
                </label>
            </div>
            <div class="form-group">
                <input type="radio" name="radio-1-2" id="radio-2" data-validate="{required:true}">
                <label for="radio-2">
                    radio 2
                </label>
            </div>
        </div>
    </div>

    <h5>Test inline input</h5>
    <div class="form-group">
        <div class="form-group-inline">
            <div class="form-group">
                <label class="label-control">
                    Lorem
                </label>
                <input type="text" class="input-control" data-validate="{required:true}">
            </div>
            <div class="form-group">
                <label class="label-control">
                    Lorem Ipsum
                </label>
                <input type="text" class="input-control" data-validate="{required:true}">
            </div>
        </div>
    </div>

    <h5>Test inline input and label</h5>
    <div class="form-group">
        <div class="form-group-inline">
            <div>
                <div class="form-group form-group-inline">
                    <label class="label-control">
                        Lorem
                    </label>
                    <input type="text" class="input-control" data-validate="{required:true}">
                </div>
            </div>
            <div>
                <div class="form-group form-group-inline">
                    <label class="label-control">
                        Lorem Ipsum
                    </label>
                    <input type="text" class="input-control" data-validate="{required:true}">
                </div>
            </div>
        </div>
    </div>

    <h5>Test columns</h5>
    <div class="flex flex-space-none flex-space-medium-sm">
        <div class="col-12 col-3-sm">
            <div class="form-group">
                <label class="label-control">
                    Lorem
                </label>
                <input type="text" class="input-control" data-validate="{required:true}">
            </div>
        </div>
        <div class="col-12 col-9-sm">
            <div class="form-group">
                <label class="label-control">
                    Lorem Ipsum
                </label>
                <input type="text" class="input-control" data-validate="{required:true}">
            </div>
        </div>
    </div>

    <h5>Test horizontal</h5>
    <div class="form-group">
        <div class="form-group-horizontal">
            <div class="col-12 col-3-sm">
                <label class="label-control">
                    Lorem
                </label>
            </div>
            <div class="col-12 col-9-sm">
                <input type="text" class="input-control" data-validate="{required:true}">
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="form-group-horizontal">
            <div class="col-12 col-3-sm">
                <label class="label-control">
                    Lorem Ipsum
                </label>
            </div>
            <div class="col-12 col-9-sm">
                <input type="text" class="input-control" data-validate="{required:true}">
            </div>
        </div>
    </div>

    <div class="form-group text-right">
        <button type="submit">Submit</button>
    </div>

</form>
