<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>

<?php $_loggedin = $this->helper('Magento\Checkout\Helper\Cart')->getCart()->getCustomerSession()->isLoggedIn(); ?>

<?php if( $_loggedin ) : ?>
    <li class="account-link">
        <a <?= /* @noEscape */ $block->getLinkAttributes() ?>>
            <?= $block->escapeHtml($block->getLabel()) ?>
        </a>
    </li>
<?php endif; ?>