<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>

<?php $_loggedin = $this->helper('Magento\Checkout\Helper\Cart')->getCart()->getCustomerSession()->isLoggedIn(); ?>

<?php if( $_loggedin ) : ?>
    <li>
        <a href="<?php echo $block->getUrl('customer/account'); ?>">
            <?php echo __('Dashboard') ?>
        </a>
    </li>
    <li>
        <a href="<?php echo $block->getUrl('customer/account'); ?>">
            <?php echo __('Billing information') ?>
        </a>
    </li>
    <li>
        <a href="<?php echo $block->getUrl('customer/address'); ?>">
            <?php echo __('Shipping address') ?>
        </a>
    </li>
    <li>
        <a href="<?php echo $block->getUrl('sales/order/history'); ?>">
            <?php echo __('My orders') ?>
        </a>
    </li>
<?php endif; ?>